export const SHOW_LOADING = 'POSTS/SHOW_LOADING';
export const HIDE_LOADING = 'POSTS/HIDE_LOADING';
export const LOAD_POSTS_SUCCESS = 'POSTS/LOAD_POSTS_SUCCESS';
export const LOAD_POSTS_ERROR = 'POSTS/LOAD_POSTS_ERROR';
export const RESET = 'POSTS/RESET';
export const SET_PAGE = 'POSTS/SET_PAGE';
export const SET_TOTAL = 'POSTS/SET_TOTAL';
