export const SHOW_LOADING = 'PROFILE/SHOW_LOADING';
export const HIDE_LOADING = 'PROFILE/HIDE_LOADING';
export const LOAD_PROFILE_SUCCESS = 'PROFILE/LOAD_PROFILE_SUCCESS';
export const LOAD_PROFILE_ERROR = 'PROFILE/LOAD_PROFILE_ERROR';
export const RESET = 'PROFILE/RESET';
export const VISIBLE_MODAL = 'PROFILE/VISIBLE_MODAL';
export const NOT_VISIBLE_MODAL = 'PROFILE/NOT_VISIBLE_MODAL';
