export const SHOW_LOADING = 'SIGNIN/SHOW_LOADING';
export const HIDE_LOADING = 'SIGNIN/HIDE_LOADING';
export const LOAD_USER_SUCCESS = 'SIGNIN/LOAD_USERS_SUCCESS';
export const LOAD_USER_ERROR = 'SIGNIN/LOAD_USERS_ERROR';
export const RESET_INFO = 'SIGNIN/RESET_INFO';
export const CHANGE_REDIRECT = 'SIGNIN/CHANGE_REDIRECT';
export const CANCEL_REDIRECT = 'SIGNIN/CANCEL_REDIRECT';
