export const SHOW_LOADING = 'USERS/SHOW_LOADING';
export const HIDE_LOADING = 'USERS/HIDE_LOADING';
export const LOAD_USERS_SUCCESS = 'USERS/LOAD_USERS_SUCCESS';
export const LOAD_USERS_ERROR = 'USERS/LOAD_USERS_ERROR';
export const RESET = 'USERS/RESET';
export const SET_PAGE = 'USERS/SET_PAGE';
export const SET_TOTAL = 'USERS/SET_TOTAL';
