export const SHOWS_LOADING = 'USER/SHOW_LOADING';
export const HIDES_LOADING = 'USER/HIDE_LOADING';
export const LOAD_USER_SUCCESS = 'USER/LOAD_USER_SUCCESS';
export const LOAD_USER_ERROR = 'USER/LOAD_USER_ERROR';
